"""Predefined skills and role-based interview question banks."""

PREDEFINED_SKILLS = [
    "python", "java", "javascript", "typescript", "react", "angular", "vue",
    "node.js", "nodejs", "django", "flask", "fastapi", "spring", "spring boot",
    "html", "css", "tailwind", "bootstrap", "sql", "mysql", "postgresql",
    "mongodb", "redis", "aws", "azure", "gcp", "docker", "kubernetes", "jenkins",
    "ci/cd", "terraform", "ansible", "git", "github", "gitlab", "rest api",
    "graphql", "microservices", "agile", "scrum", "machine learning", "deep learning",
    "tensorflow", "pytorch", "pandas", "numpy", "scikit-learn", "nlp", "computer vision",
    "data analysis", "data visualization", "power bi", "tableau", "spark", "hadoop",
    "etl", "linux", "bash", "networking", "cybersecurity", "penetration testing",
    "siem", "firewall", "oauth", "jwt", "oauth2", "api", "oop", "design patterns",
    "system design", "devops", "cloud", "serverless", "lambda", "ec2", "s3",
    "c++", "c#", ".net", "go", "golang", "rust", "ruby", "rails", "php", "laravel",
    "selenium", "pytest", "junit", "unit testing", "integration testing",
]

INTERVIEW_ROLES = [
    "Software Engineer",
    "Python Developer",
    "Java Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "DevOps Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Cloud Engineer",
    "Cybersecurity Analyst",
]

ROLE_KEYWORDS = {
    "Software Engineer": ["python", "java", "oop", "system design", "git", "sql", "api"],
    "Python Developer": ["python", "django", "flask", "fastapi", "oop", "pytest", "rest api"],
    "Java Developer": ["java", "spring", "spring boot", "oop", "sql", "junit", "microservices"],
    "Frontend Developer": ["javascript", "react", "html", "css", "typescript", "vue", "angular"],
    "Backend Developer": ["python", "java", "node.js", "rest api", "sql", "docker", "microservices"],
    "Full Stack Developer": ["javascript", "react", "python", "django", "sql", "docker", "rest api"],
    "DevOps Engineer": ["docker", "kubernetes", "ci/cd", "aws", "jenkins", "terraform", "linux"],
    "Data Scientist": ["python", "pandas", "numpy", "machine learning", "sql", "scikit-learn", "data visualization"],
    "Machine Learning Engineer": ["python", "tensorflow", "pytorch", "deep learning", "nlp", "ml", "docker"],
    "Cloud Engineer": ["aws", "azure", "gcp", "docker", "kubernetes", "terraform", "networking"],
    "Cybersecurity Analyst": ["cybersecurity", "networking", "siem", "penetration testing", "firewall", "linux"],
}

INTRO_QUESTIONS = [
    "Tell me about yourself and what motivated you to apply for this role.",
    "Walk me through your resume — highlight your most relevant experience.",
]

BEHAVIORAL_QUESTIONS = [
    "Tell me about a challenging project you worked on. How did you handle it?",
    "Describe a time you had a conflict with a teammate. How did you resolve it?",
    "Give an example of when you had to learn something new quickly under pressure.",
]

CLOSING_QUESTIONS = [
    "Do you have any questions for us about the role or the team?",
    "Is there anything else you'd like us to know that we haven't covered?",
]

ROLE_TECHNICAL_QUESTIONS = {
    "Software Engineer": [
        ("What is the difference between a stack and a queue?", "easy", ["stack", "queue", "data structure"]),
        ("Explain OOP pillars with a real-world example.", "easy", ["oop", "encapsulation", "inheritance", "polymorphism"]),
        ("How would you design a URL shortener at a high level?", "medium", ["system design", "database", "hash", "cache"]),
        ("What is time complexity of binary search?", "easy", ["o(log n)", "binary search", "complexity"]),
        ("Explain REST vs GraphQL — when would you pick each?", "medium", ["rest", "graphql", "api"]),
        ("How do you handle database migrations in production?", "medium", ["migration", "database", "deployment"]),
        ("Describe how you would debug a memory leak.", "hard", ["debug", "memory", "profiling"]),
        ("What strategies do you use for writing testable code?", "medium", ["testing", "unit test", "mock"]),
    ],
    "Python Developer": [
        ("What are Python decorators and when would you use them?", "easy", ["decorator", "function", "wrapper"]),
        ("Explain list vs tuple vs set in Python.", "easy", ["list", "tuple", "set", "mutable"]),
        ("How does Django's ORM handle N+1 query problems?", "medium", ["django", "orm", "select_related", "prefetch"]),
        ("What is a context manager? Give an example.", "easy", ["with", "context manager", "__enter__"]),
        ("How do you structure a REST API in Django REST Framework?", "medium", ["drf", "serializer", "viewset", "api"]),
        ("Explain async/await in Python 3.", "medium", ["asyncio", "async", "await", "coroutine"]),
        ("How would you optimize a slow Django view?", "hard", ["cache", "query", "optimization", "django"]),
        ("Describe a Python project you built and the architecture choices.", "medium", ["project", "architecture", "python"]),
    ],
    "Java Developer": [
        ("Explain JVM, JRE, and JDK.", "easy", ["jvm", "jre", "jdk"]),
        ("What is the difference between abstract class and interface in Java?", "easy", ["abstract", "interface", "java"]),
        ("How does Spring Boot auto-configuration work?", "medium", ["spring boot", "autoconfiguration", "bean"]),
        ("Explain Java memory model — heap vs stack.", "medium", ["heap", "stack", "memory", "garbage collection"]),
        ("What are Java streams and how do they help?", "medium", ["stream", "lambda", "functional"]),
        ("How do you handle concurrency in Java?", "hard", ["thread", "synchronized", "executor", "concurrency"]),
        ("Describe microservices communication patterns you've used.", "hard", ["microservices", "rest", "message queue"]),
        ("Walk through building a REST API with Spring.", "medium", ["spring", "rest", "controller", "service"]),
    ],
    "Frontend Developer": [
        ("Explain the CSS box model.", "easy", ["box model", "margin", "padding", "border"]),
        ("What is the virtual DOM in React?", "easy", ["virtual dom", "react", "reconciliation"]),
        ("How do you manage state in a large React application?", "medium", ["state", "redux", "context", "react"]),
        ("Explain event delegation in JavaScript.", "easy", ["event", "bubbling", "delegation"]),
        ("What is CORS and how do you handle it?", "medium", ["cors", "headers", "api", "security"]),
        ("How do you optimize frontend performance?", "hard", ["lazy loading", "bundle", "lighthouse", "performance"]),
        ("Compare CSS Grid vs Flexbox — when to use each?", "medium", ["grid", "flexbox", "layout"]),
        ("Describe accessibility best practices you follow.", "medium", ["a11y", "aria", "accessibility", "semantic"]),
    ],
    "Backend Developer": [
        ("What is idempotency in REST APIs?", "medium", ["idempotent", "rest", "http"]),
        ("Explain database indexing and when it helps.", "easy", ["index", "database", "query"]),
        ("How do you design authentication for a microservice?", "hard", ["jwt", "oauth", "authentication"]),
        ("What is connection pooling and why use it?", "medium", ["connection pool", "database", "performance"]),
        ("Describe caching strategies you've implemented.", "medium", ["cache", "redis", "ttl", "invalidation"]),
        ("How do you handle rate limiting?", "medium", ["rate limit", "throttle", "api"]),
        ("Explain message queues vs direct HTTP calls.", "medium", ["queue", "rabbitmq", "kafka", "async"]),
        ("How would you scale a read-heavy API?", "hard", ["replica", "cache", "load balancer", "scale"]),
    ],
    "Full Stack Developer": [
        ("How do you structure a monorepo vs separate frontend/backend repos?", "medium", ["monorepo", "architecture", "deployment"]),
        ("Explain JWT authentication flow end-to-end.", "medium", ["jwt", "token", "authentication", "api"]),
        ("How do you deploy a full stack app with Docker?", "medium", ["docker", "compose", "deployment"]),
        ("What is your approach to API versioning?", "easy", ["versioning", "api", "backward compatible"]),
        ("How do you sync frontend types with backend schemas?", "medium", ["typescript", "openapi", "schema"]),
        ("Describe SSR vs CSR — tradeoffs.", "medium", ["ssr", "csr", "next.js", "seo"]),
        ("How do you handle file uploads securely?", "hard", ["upload", "validation", "storage", "security"]),
        ("Walk through a feature you built from DB to UI.", "medium", ["full stack", "feature", "end to end"]),
    ],
    "DevOps Engineer": [
        ("What is the difference between Docker and Kubernetes?", "easy", ["docker", "kubernetes", "container", "orchestration"]),
        ("Explain a CI/CD pipeline you've built.", "medium", ["ci/cd", "jenkins", "github actions", "pipeline"]),
        ("How do you manage secrets in production?", "hard", ["secrets", "vault", "environment", "security"]),
        ("What is Infrastructure as Code? Tools you've used?", "medium", ["terraform", "ansible", "iac"]),
        ("How do you monitor application health in production?", "medium", ["prometheus", "grafana", "monitoring", "alert"]),
        ("Explain blue-green vs canary deployments.", "medium", ["deployment", "canary", "blue green"]),
        ("How do you troubleshoot a pod CrashLoopBackOff?", "hard", ["kubernetes", "logs", "debug", "pod"]),
        ("Describe your experience with AWS services for deployment.", "medium", ["aws", "ec2", "ecs", "eks", "lambda"]),
    ],
    "Data Scientist": [
        ("Explain bias-variance tradeoff.", "easy", ["bias", "variance", "overfitting", "underfitting"]),
        ("How do you handle missing data in a dataset?", "easy", ["missing", "imputation", "pandas", "data cleaning"]),
        ("What is cross-validation and why use it?", "medium", ["cross validation", "k-fold", "model evaluation"]),
        ("Explain precision vs recall — when to optimize each.", "medium", ["precision", "recall", "f1", "metrics"]),
        ("How would you detect outliers in a dataset?", "medium", ["outlier", "iqr", "z-score", "anomaly"]),
        ("Describe a machine learning project from problem to deployment.", "hard", ["ml", "pipeline", "model", "deployment"]),
        ("What is feature engineering? Give examples.", "medium", ["feature", "engineering", "encoding", "scaling"]),
        ("How do you communicate insights to non-technical stakeholders?", "medium", ["visualization", "storytelling", "dashboard"]),
    ],
    "Machine Learning Engineer": [
        ("Explain the training vs inference pipeline.", "easy", ["training", "inference", "model", "pipeline"]),
        ("How do you version ML models in production?", "medium", ["mlops", "versioning", "registry", "deployment"]),
        ("What is transfer learning? When do you use it?", "medium", ["transfer learning", "pretrained", "fine tuning"]),
        ("How do you handle class imbalance?", "medium", ["imbalance", "smote", "weighting", "sampling"]),
        ("Explain gradient descent and learning rate.", "easy", ["gradient", "learning rate", "optimizer"]),
        ("How do you deploy a model as an API?", "hard", ["serving", "api", "docker", "latency"]),
        ("What metrics do you use for NLP vs computer vision tasks?", "medium", ["bleu", "accuracy", "iou", "metrics"]),
        ("Describe optimizing model inference for low latency.", "hard", ["quantization", "onnx", "tensorrt", "optimization"]),
    ],
    "Cloud Engineer": [
        ("Compare IaaS, PaaS, and SaaS with examples.", "easy", ["iaas", "paas", "saas", "cloud"]),
        ("How do you design a highly available architecture on AWS?", "hard", ["availability", "multi-az", "load balancer", "aws"]),
        ("Explain VPC, subnets, and security groups.", "medium", ["vpc", "subnet", "security group", "networking"]),
        ("What is the shared responsibility model in cloud security?", "medium", ["security", "compliance", "shared responsibility"]),
        ("How do you estimate cloud costs and optimize spend?", "medium", ["cost", "reserved instance", "spot", "optimization"]),
        ("Describe disaster recovery strategies in the cloud.", "hard", ["backup", "rpo", "rto", "disaster recovery"]),
        ("How do you automate infrastructure provisioning?", "medium", ["terraform", "cloudformation", "automation"]),
        ("Explain serverless architecture tradeoffs.", "medium", ["lambda", "serverless", "cold start", "scale"]),
    ],
    "Cybersecurity Analyst": [
        ("Explain the CIA triad in cybersecurity.", "easy", ["confidentiality", "integrity", "availability", "cia"]),
        ("What is the difference between IDS and IPS?", "easy", ["ids", "ips", "intrusion", "detection"]),
        ("How do you respond to a suspected phishing incident?", "medium", ["phishing", "incident response", "soc"]),
        ("Explain common OWASP Top 10 vulnerabilities.", "medium", ["owasp", "injection", "xss", "csrf"]),
        ("What is zero trust architecture?", "hard", ["zero trust", "authentication", "microsegmentation"]),
        ("How do you perform a basic vulnerability assessment?", "medium", ["vulnerability", "scan", "cve", "assessment"]),
        ("Describe SIEM and how you use it for threat detection.", "medium", ["siem", "logs", "correlation", "alert"]),
        ("What steps do you take for secure remote access?", "medium", ["vpn", "mfa", "remote", "access control"]),
    ],
}
