# Generated by Django 6.0.4 on 2026-05-17 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_filename', models.CharField(blank=True, max_length=255)),
                ('job_description', models.TextField()),
                ('ats_score', models.FloatField(default=0)),
                ('keyword_score', models.FloatField(default=0)),
                ('skill_score', models.FloatField(default=0)),
                ('matched_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('resume_skills', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Python Developer', 'Python Developer'), ('Java Developer', 'Java Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('DevOps Engineer', 'DevOps Engineer'), ('Data Scientist', 'Data Scientist'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Cloud Engineer', 'Cloud Engineer'), ('Cybersecurity Analyst', 'Cybersecurity Analyst')], max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('questions', models.JSONField(default=list)),
                ('resume_skills', models.JSONField(default=list)),
                ('job_description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=25)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('technical_score', models.FloatField(blank=True, null=True)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('report', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('phase', models.CharField(max_length=32)),
                ('difficulty', models.CharField(blank=True, max_length=16)),
                ('answer_text', models.TextField()),
                ('score', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('keywords_found', models.JSONField(default=list)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.interviewsession')),
            ],
            options={
                'ordering': ['question_index'],
                'unique_together': {('session', 'question_index')},
            },
        ),
    ]
